version: '3.8'

services:
  nextmu-auth:
    restart: 'always'
    networks:
      - 'nextmu'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkeyFromEnv --tlsMode disabled'
    env_file:
      - ./environments/zitadel.env
    volumes:
      - ./zitadel-machinekey:/machinekey
    depends_on:
      nextmu-postgres:
        condition: 'service_healthy'
    ports:
      - '8080:8080'
      
  nextmu-postgres:
    restart: 'always'
    image: postgres:16-alpine
    env_file:
      - ./environments/postgres.env
    networks:
      - 'nextmu'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  nextmu-mongodb:
    restart: 'always'
    image: mongo:7-jammy
    env_file:
      - ./environments/mongo.env
    networks:
      - 'nextmu'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://$$MONGO_INITDB_ROOT_USERNAME:$$MONGO_INITDB_ROOT_PASSWORD@localhost:27017/test?authSource=admin --quiet | grep -q 1
      interval: '10s'
      timeout: '10s'
      retries: 5
      start_period: '20s'
    volumes:
      - ./mongodb-data:/data
    ports:
      - '127.0.0.1:27017:27017'

  nextmu-redis:
    restart: 'always'
    image: redis:7-alpine
    env_file:
      - ./environments/redis.env
    networks:
      - 'nextmu'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: '10s'
      timeout: '5s'
      retries: 3
      start_period: '20s'
    volumes:
      - ./redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'

networks:
  nextmu:
