services:
  nextmu-auth:
    restart: 'always'
    networks:
      - 'nextmu'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkeyFromEnv --tlsMode disabled'
    env_file:
      - ./environments/zitadel.env
    volumes:
      - ./zitadel-machinekey:/machinekey
    depends_on:
      nextmu-postgres:
        condition: 'service_healthy'
    ports:
      - '8080:8080'
      
  nextmu-postgres:
    restart: 'always'
    image: postgres:16-alpine
    env_file:
      - ./environments/postgres.env
    networks:
      - 'nextmu'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod", "-U", "$$POSTGRES_USER"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  nextmu-mongodb:
    restart: 'always'
    image: mongo:7-jammy
    command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/replica.key"]
    entrypoint:
        - bash
        - -c
        - |
            chmod 400 /data/replica.key
            chown 999:999 /data/replica.key
            exec docker-entrypoint.sh $$@ 
    env_file:
      - ./environments/mongo.env
    networks:
      - 'nextmu'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://$$MONGO_INITDB_ROOT_USERNAME:$$MONGO_INITDB_ROOT_PASSWORD@localhost:27017/test?authSource=admin&replicaSet=rs0&directConnection=true --quiet | grep -q 1
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    volumes:
      - ./environments/mongo.key:/data/replica.key
      - ./mongodb-data/configdb:/data/configdb
      - ./mongodb-data/db:/data/db
    ports:
      - '127.0.0.1:27017:27017'
      
  nextmu-mongosetup:
    restart: "no"
    image: mongo:7-jammy
    depends_on:
      - nextmu-mongodb
    env_file:
      - ./environments/mongo.env
    networks:
      - 'nextmu'
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh mongodb://$$MONGO_INITDB_ROOT_USERNAME:$$MONGO_INITDB_ROOT_PASSWORD@nextmu-mongodb:27017/test?authSource=admin&directConnection=true --eval 'rs.initiate()'"]

  nextmu-redis:
    restart: 'always'
    image: bitnami/redis:7.0
    env_file:
      - ./environments/redis.env
    networks:
      - 'nextmu'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
      interval: '10s'
      timeout: '5s'
      retries: 3
      start_period: '20s'
    volumes:
      - ./redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'

networks:
  nextmu:
